ruby-implementation/config/routes.rb
Rails.application.routes.draw do

  # Routes for sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web, :at => '/sidekiq'

  # Routes for login
  root 'users#homepage'
  get 'homepage' => 'users#homepage'
  get 'user/new' => 'users#new'
  get 'user/login' => 'users#login'
  post 'users/signup' => 'users#signup'
  post 'users/login' => 'users#login_check'
  post 'user/show' => 'users#show'
  
  get 'user/logout' => 'users#logout'
  
  # Routes for Urls
  resources :urls
  get 'url/long' => 'urls#search_longurl' 
  post 'urls/long' => 'urls#create_shorturl'

  # Routes for urlreport
  get 'urlreport/new' => 'urlreports#new'
  get 'urlreport' => 'urlreports#index' 
  
  #Routed for elastic search
  get 'url/search' =>'search#search'

  #Routes for short domain
  resources :short_domain
  post 'short_domain/create' => 'short_domain#create_short_domain'
  
end

ruby-implementation/app/models/url.rb
require 'elasticsearch/model'
require 'domainatrix'
class Url < ApplicationRecord
  
  #Elastic Search
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  searchkick
  index_name('urls')

  #Validations of url
  validates :longurl, presence: true , :length => { :in => 3..1000 } , uniqueness: true
  validates_format_of :longurl, with: /\A(?:(?:http|https):\/\/)?([-a-zA-Z0-9.]{2,256}\.[a-z]{2,4})\b(?:\/[-a-zA-Z0-9@,!:%_\+.~#-?&\/\/=]*)?\z/
  validates :shorturl, presence: true , :length => { :in => 3..1000 } , uniqueness: true
  validates_format_of :shorturl, with: /\A(?:(?:http|https):\/\/)?([-a-zA-Z0-9.]{2,256}\.[a-z]{2,4})\b(?:\/[-a-zA-Z0-9@,!:%_\+.~#-?&\/\/=]*)?\z/
  
  #mapping for elastic search
  settings index: {
   number_of_shards: 1,
   number_of_replicas: 0,
   analysis: {
      analyzer: {
         pattern: {
            type: 'pattern',
            pattern: "\\s|_|-|\\.",
            lowercase: true
         },
       }
     }
   }do
    mapping do
      indexes :short_url, type: 'text', analyzer: 'english' do
        indexes :keyword, analyzer: 'keyword'
        indexes :pattern, analyzer: 'pattern'
      end
      indexes :long_url, type: 'text', analyzer: 'english' do
        indexes :keyword, analyzer: 'keyword'
        indexes :pattern, analyzer: 'pattern'
      end
    end
  end

  #Sidekiq 
  after_create :background_process
  def background_process
    ConvertWorker.perform_async
  end

  #check all input parameters
  def check_params(longurl)
    if longurl==""
      return false
    else 
      short_domain =  ShortDomain.where(domain: Domainatrix.parse(longurl).domain + '.' + Domainatrix.parse(longurl).public_suffix).first
      if short_domain == nil
        return false
      else
        return true
      end
    end
  end

  #Create shorturl from longurl
  def create_short_url(url_params)  
    url  = Url.new(url_params)
    url.suffix= url.create_suffix(url_params[:longurl],0)
    while url.unique(url.suffix) == false
      url.suffix = url.create_suffix(url_params[:longurl],1)
    end
    domain = Domainatrix.parse(url_params[:longurl]).domain + '.' + Domainatrix.parse(url_params[:longurl]).public_suffix
    short_domain = ShortDomain.where(domain: domain).first[:prefix]
    url.shorturl = "http://" + short_domain +'/'+ url.suffix
    if url.save
      return url
    else
      return nil
    end
  end

  #Search Long Url in DB
  def find_long(longurl) 
     Url.where(longurl: longurl).first
  end

  #Redis search shorturl
  def find_short(shorturl)        
    Rails.cache.fetch("#{shorturl}", expires_in: 100.hours) do
        Url.where(shorturl: shorturl).first
    end
  end

  #Redis search suffix
  def find_suffix(suffix)          
    Rails.cache.fetch("#{suffix}", expires_in: 100.hours) do
      Url.where(suffix: suffix).first
    end
  end

  #Check whether generated suffix is unique or not
  def unique(suffix)         
    check = Url.where(suffix: suffix).first
    if check == nil
      return true
    else
      return false
    end
  end

  #Calculate the ascii value of url
  def ascii_value(url)
    ascii_value = 0;
    url.each_char {|url| ascii_value += url.ord}
    return ascii_value
  end

  #Calculate the suffix for  the shorturl
  def create_suffix(longurl,flag)
    ascii_value = ascii_value(longurl)
    if(flag == 1)
      ascii_value = ascii_value + rand(100..1000)
    end
    suffix = ""
    map_hash = "ABCDEFGHIJKLMNO%PQRSTUVWXYZ0123&456789abcdefghi$jklmnopqrstuvwx*yz" #base(66)
    while ascii_value!=0
      suffix += map_hash[ascii_value % 66]
      ascii_value = ascii_value/10
    end
    return suffix
  end
end

  

ruby-implementation/app/controllers/urls_controller.rb
require 'domainatrix'
class UrlsController < ApplicationController

=begin
  **Description:** This action will check whether the user is already logged in or not .If not it will 
  redirect it to the user_login_path.If logged in it will create a new instance of user object and 
  render the new.html.erb file
=end
  def new
    @url = Url.new
  end

  
=begin
  **Common Name:** Create shorturl from the input longurl and domain
  **End points:** Other services
  **Request Type:** POST
  **Route:** urls_long_path
  **url:**  URI("http://localhost:3000/urls/long")
  **Paramas:** { "longurl" : " ","domain"  : " "}
  **Cookies:** {
    Name : _project_intern_session
    Value : 
    Domain : localhost
    HttpOnly : True
    Secure : false
  }
  **Content-Type:** application/json; charset=utf-8
  **Input Type:** JSON
  **Input Fields:** longurl,domain 
  **Output Type:** JSON
  **Output Fields:** status, shorturl
  **Host:** localhost:3000
  **Cache-Control:** no-cache
  **Custom Status Messages:** {
    a)Message : "already_exist"
    Status  : 200 OK
    Description : Since the input longurl is already existed in the database,it will just find the shorturl correponding to that longurl in the database and return that shorturl along with above mentioned message.

    b)Message  : "new created shorturl"
    Status   :  200 OK
    Description : If the input longurl is not already present in the database,and new shorturl is created correponding to that longurl and domain.It is than saved in the database and return the newly generated shorturl alongwith the above message.

    c)Message : "error occured"
    Status : 404 not-dound
    Description : If the input url is not according to the validations mentioned in the url model ,than an error message will be displayed to the user as mentioned above

    d)Status : 500 Internal server error
    Description : If the longurl is not defined in the input params

    e)Message : "Short Domain not found,please add short domain" 
    Status : 404 not-found
    Description : if domain entered by user in not in shortdomain table

    f)Message : "Domain Name does not matched" 
    Status : 404 not-found
    Description : if domain entered by user in not match longurl domain
  }   
=end
  
  def create_shorturl
    # respond_to do |format|
    #   format.json{
    #     url=Url.new
    #     response = url.check_params(params[:longurl])
    #     puts response
    #     if response!=true
    #       render json: { 'message' => "Invalid longurl value or Domain not registered"}
    #     else
    #       if url.find_long(params[:longurl]) != nil
    #         render json: { 'message' => 'longurl already exist', 'shorturl' => url.shorturl }
    #       else       
    #         url=Url.new
    #         if url.create_short_url(url_params) == nil
    #           render json: { 'message' => 'error occured' }, status: :not_found
    #         else
    #           render json: { 'message' => 'new created shorturl', 'shorturl' => url.shorturl }
    #         end
    #       end
    #     end
    #   }   
    #   format.html{
    @url=Url.new
    response = @url.check_params(params[:url][:longurl])
    if response != true
      flash[:notice]="Invalid longurl value or Domain not registered"
      render 'new'
    else
      if @url.find_long(params[:url][:longurl]) != nil
        redirect_to @url.find_long(params[:url][:longurl])
      else
        @url=@url.create_short_url(url_params)
        if @url != nil
          render 'show' 
        else
          flash[:notice] = "Invalid long Url"
          render 'new'  
        end
      end
    end
  end

=begin
  **Common Name:** Show the url by search it in database via params[:id]
  **Request Type:** GET
  **Routes:** url_path
  **Description:** Check the authentication session and if logged in,it will display the longurl,shorturl,domain and suffix corresponding to the url
=end 
  def show
    @url = Url.find(params[:id])
  end
  
=begin
  **Common Name:**Search for longurl from input shorturl
  **End points:** Other services
  **Request Type** : GET
  **Routes** : url_long_path
  **url:** URI("http://localhost:3000/url/long?shorturl=")
  **Params:** KEY->shorturl , VALUE-> '' , DESCRIPTION-> 'ShortUrl Input to get longurl in return'
  **Cookies:**{
    Name : _project_intern_session
    Value : 
    Domain : localhost
    HttpOnly : True
    Secure : false
  }
  **Content-Type:** application/json; charset=utf-8
  **Output Type:** JSON
  **Output Fields:** status,longurl
  **Host:** localhost:3000
  **Cache-Control:**  no-cache
  **Custom Status Messages:**{
    a)Message : "longurl corresponding to shorturl is found"
    Status  : 404 not-found
    Description : Since the input shorturl is already existed in the database,it will just find the longurl correponding to that shorturl in the database and return that longurl along with above mentioned message.

    b)Message  : "Invalid shorturl"
    Status   :  200 OK
    Description : If the input shorturl is not already present in the database,it will return the above message

    c)Status : 404 not-found
    Description : If the shorturl key is not mentioned in the input params
  }
=end
  def search_longurl
    # respond_to do |format|
    #   format.json{
    #     url=Url.new
    #     if(params[:shorturl]==nil)
    #       render json: { 'message' => 'Input Shorturl is Empty' }, status: :not_found 
    #     else
    #       if(params[:shorturl][0..6]!="http://")
    #         url = url.find_suffix(params[:shorturl])
    #       else
    #         url = url.find_short(params[:shorturl])
    #       end
    #       if url!=nil
    #         render json: { 'message' => 'longurl corresponding to shorturl is found', 'longurl' => url.longurl }
    #       else
    #         render json: { 'message' => 'Invalid shorturl' } ,status: :not_found    
    #       end
    #     end
    #   }
    #   format.html{
    @url=Url.new
    if(params[:url][:shorturl]==nil)
      flash[:notice] = "Input Shorturl is Empty"
      redirect_to new_url_path
    else
      if(params[:url][:shorturl][0..6]!="http://")
        @url = @url.find_suffix(params[:url][:shorturl])
      else
        @url = @url.find_short(params[:url][:shorturl])
      end
      if @url!=nil
        redirect_to @url
      else
        @url=Url.new
        flash[:notice] = "Invalid Short Url"
        redirect_to new_url_path
      end
    end 
  end

  private
    def url_params
      params.require(:url).permit(:longurl, :domain, :shorturl )
    end
end

ruby-implementation/app/views/urls/index.html.erb
<style>
  button{
    font-family:Georgia,sans-serif;
    padding:2px;
    font-size:1.2em;
    margin:10px
  }
  #display {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  #display td, #display th {
    border: 1px solid #ddd;
    padding: 8px;
  }
  #display tr:nth-child(even){background-color: #f2f2f2;}
  #display tr:hover {background-color: #ddd;}
  #display th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: midnightblue;
    color: white;
  }
</style>
  
  <table id='display'>
    <tr>
      <th>LongUrl</th>
      <th>Shorturl</th>
    </tr>
    <% @url.each do |url| %>
      <tr>
        <td><%= url.longurl %></td>
        <td><%= url.shorturl %></td>
      </tr>
    <% end %>
  </table>
<br/>
<button><%= link_to 'Back', new_url_path %></button>

ruby-implementation/app/views/urls/new.html.erb
<style>
  span{
    color:midnightblue;
    font-size:1.2em;
    padding:5px;
    font-family:Georgia,sans-serif;
    text-transform: capitalize;
  }
	.form{
		border:1px solid black;
		padding:10px;
		margin:15px;
		position:relative;
	}
  button{
    text-align:center;
    padding:2px;
    font-family:Georgia,sans-serif;
    font-size:1.2em;
  }
  .btn-group button {
  position:relative;
  left:1%;
  background-color: lightblue; 
  border: 1px solid gray; 
  color: white; 
  padding: 10px 24px; 
  cursor: pointer; 
  float: left; 
  } 

  /* Clear floats (clearfix hack) */
  .btn-group:after {
    content: "";
    clear: both;
    display: table;
  }

  .btn-group button:not(:last-child) {
    border-right: none; 
  }
</style>
<div>
  <h2>URL SHORTNER</h2>
  <span>Hi <%= session[:username] %></span>
  <div class="form">
    <%= form_for @url , url: urls_long_path do |form| %>
      <p>Long Url: <%= form.text_field :longurl%> </br></p>
      <p>Find : <%=  form.submit 'Search' %></p><br/>
    <% end %>
  </div>

  <div class="form">
    <%= form_for @url, url: url_long_path, method: :get do |form| %>
      <p> Short Url / Suffix: <%= form.text_field :shorturl%> </br></p>
      <p>Find : <%=  form.submit  'Search'%><br/></p>
    <% end %>
  </div>

  <div class="errors">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>

  <div class="btn-group">
    <button>Add ShortDomain : <%= link_to 'create',new_short_domain_path %></button>
    <button>Short Domain List: <%= link_to 'showall', short_domain_index_path  %> </button>
    <button>Logout : <%= link_to 'logout',user_logout_path  %> </button>
    <button>Daily Report : <%= link_to 'index',urlreport_new_path  %> </button>
    <button>Elastic Search : <%= link_to 'search',url_search_path  %> </button>
  </div>
</div>

ruby-implementation/app/views/urls/show.html.erb
<style>
  button{
    color:black;
    font-size:1.1em;
    text-align:center;
    font-family:sans-serif;
  }
  #display {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  #display td, #display th {
    border: 1px solid #ddd;
    padding: 8px;
  }
  ##display tr:nth-child(even){background-color: #f2f2f2;}
  #display tr:hover {background-color: #ddd;}
  #display th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: midnightblue;
    color: white;
  }
</style>
<div id = "display">
  <table>
    <tr>
      <th>LONGURL</th>
      <th>SHORTURL</th>
      <th>SUFFIX</th>
    </tr>
    <tr>
      <td><%= @url.longurl %></td>
      <td><%= @url.shorturl %></td>
      <td><%= @url.suffix %></td>
    </tr>
  </table>
</div><br/>
<button><%= link_to 'Back', new_url_path %></button>