ruby-implementation/config/routes.rb
Rails.application.routes.draw do

  # Routes for sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web, :at => '/sidekiq'

  # Routes for login
  root 'users#homepage'
  get 'homepage' => 'users#homepage'
  get 'user/new' => 'users#new'
  get 'user/login' => 'users#login'
  post 'users/signup' => 'users#signup'
  post 'users/login' => 'users#login_check'
  post 'user/show' => 'users#show'
  
  get 'user/logout' => 'users#logout'
  
  # Routes for Urls
  resources :urls
  get 'url/long' => 'urls#search_longurl' 
  post 'urls/long' => 'urls#create_shorturl'

  # Routes for urlreport
  get 'urlreport/new' => 'urlreports#new'
  get 'urlreport' => 'urlreports#index' 
  
  #Routed for elastic search
  get 'url/search' =>'search#search'

  #Routes for short domain
  resources :short_domain
  post 'short_domain/create' => 'short_domain#create_short_domain'
  
end

ruby-implementation/app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true 
  validates_length_of :password, :in => 6..200, :on => :create

  def create_user(user_params)
  	@user = User.new(user_params)
    @user.password = UsersHelper.password_convert(user_params[:password])
    if @user.save
    	return @user
    else
    	return nil
    end
  end
end

ruby-implementation/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # skip_before_action :check_session, only: [:login, :new, :login_check]

=begin
  **Request Type:** GET
  **Routes:** user_new_path
  **URI Pattern:** /users/new
  **Description:** Create a new instance of user object  in order for singup page rendering 
=end
  def new
    @user = User.new
  end


=begin
  **Request Type:** GET
  **Routes:** user_login_path
  **URI Pattern:** /user/log
  **Description:** Create a new instance of user object in order for login page rendering 
=end
  def login
    @user = User.new
  end


=begin
  **Request Type:** POST
  **Routes:** users_signup_path
  **URI Pattern:** /users/signup
  **Params:** username, email, passwords name, password_confirmation
  **Description:** This action searches the database first with email and than with username in order to get whether the 
  username or email is already present or not.If present it will display a message to the user whether the 
  "User already exist" or "Username already taken ".If none of the above two happens ,it will call a create_user function
  defined in user model.Input to the method is username,password and email.If the model method successfully saves the user 
  it will set session via set_session action and than redirect it to the new_url_path.If noty saved it will redirect it 
  to signup page again   
=end
  def signup
    @user = User.new
    if (User.where(email: params[:user][:email]).first)
      flash[:notice] = "User Already Exist"
      render 'new'
    elsif(User.where(username: params[:user][:username]).first)
      flash[:notice] = "Username Already Taken"
      render 'new'
    else
      @user = @user.create_user(user_params)
      if @user !=nil
        set_session
      else
        redirect_to user_new_path  
      end
    end
  end


=begin
  **Request Type: POST
  **Route Path: users_login
  **URI Pattern: /users/login
  **Params:** emailid,password 
  **Description:** This action take email and password as input.If the email and password matches the entry in the
   database.If the entry does not matches it means either the user is not logged in or the email/password is not 
   correct.If entry matches it will call set_session action.
=end
  def login_check
    flash[:notice] = ""
     @user = User.where(email: params[:user][:email], password: UsersHelper.password_convert(params[:user][:password])).first
    if (@user!=nil)
      set_session
    else
      flash[:notice] = "Invalid Email or Password"
      redirect_to user_login_path
    end
  end


=begin 
  **Description:** This will set the session according to the current user with session expiry time of 20 minutes
=end
  def set_session
    session[:id]=@user[:id]
    session[:username]=@user[:username]
    session[:authenticate] = true
    session[:expires_at] = Time.current + 20.minutes
    redirect_to new_url_path #redirect to the url page
  end
  
=begin
  **Request Type:** GET
  **Routes:** urls_path
  **URI pattern:**/urls
  **Description:** Indexes all the records in the url table and show their field on index.html.erb view page.
=end 
  def index
    @user = User.all.order("id ASC")
  end
=begin
  **Request Type:** GET
  **Route Path:** user_logout
  **URI Pattern:** /user/logout
  **Description:** This action will reset the session and render the login page again
=end
  def logout
    session[:id]=nil
    session[:username]=nil
    session[:authenticate]=false
    session[:expire_at]=nil
    flash[:notice] = "Logged out"
    @user = User.new
    render 'login'
  end

  

  private
  def user_params
    params.require(:user).permit(:username , :email, :password)
  end
end

ruby-implementation/app/helpers/users_helper.rb
module UsersHelper
	def self.password_convert(password)
		Digest::MD5.hexdigest password
	end
end

ruby-implementation/app/views/users/homepage.html.erb
<style>
  h2{
    text-align:center;
    color:midnightblue;
    font-family:Georgia;
  }
</style>
<div class='container-fluid'>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Housing.com</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "SignUp" , user_new_path %></li>
        <li> <%= link_to "LogIn" , user_login_path %></li>
      </ul>
    </div>
  </nav>
  <div class="row"></div>
</div>

ruby-implementation/app/views/users/login.html.erb
<style>
  *{
    padding:5px;
    margin:1px;
    font-family:Georgia,sans-serif;
      }
  .Login_Form{
    border:1px solid black;
    font-family:Georgia,sans-serif;
    text-align:center;

  }
  h2{
    color:midnightblue;
    text-align:center;

  }
  button{
    text-align:left;
  }
</style>
<h2><i>WELCOME TO LOGIN PAGE</i></h2>
<div class="Login_Form">
  <h1>Login</h1>
  <%= form_for @user, :url => users_login_path do |form| %>
    <p> Email:</br> <%= form.text_field :email%> </p>
    <p> Password:</br> <%= form.password_field :password%></p>
    <%= form.submit :login_new %>
  <% end %>
  <div class="errors">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
  <button>SignUp : <%= link_to "signup" , user_new_path %></button>
</div>

ruby-implementation/app/views/users/new.html.erb
<style>
  *{
    padding:5px;
    margin:1px;
    font-family:Georgia,sans-serif;
      }
  .Sign_Form{
    border:1px solid black;
    font-family:Georgia,sans-serif;
    text-align:center;

  }
  h2{
    color:midnightblue;
    text-align:center;

  }
  button{
    text-align:left;
  }
</style>

<h2><i>WELCOME TO SIGN UP PAGE</i></h2>

<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for @user, :url => users_signup_path do |form| %>
    <p> Username:<br/><%= form.text_field :username%> </p>
    <p> Email:<br/><%= form.text_field :email%> </p>
    <p> Password:<br/> <%= form.password_field :password%></p>
    <p> Password Confirmation:<br/> <%= form.password_field :password_confirmation%> </p>
    <%= form.submit :signup %>
  <% end %>
  <div class="errors">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <% if @user.errors.any? %>
      <ul class="Signup_Errors">
      <% for message_error in @user.errors.full_messages %>
        <li>* <%= message_error %></li>
      <% end %>
      </ul> 
    <% end %>
  </div>
  <button>Login : <%= link_to "login" , user_login_path %></button>
</div>