ruby-implementation/config/routes.rb
Rails.application.routes.draw do

  # Routes for sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web, :at => '/sidekiq'

  # Routes for login
  root 'users#homepage'
  get 'homepage' => 'users#homepage'
  get 'user/new' => 'users#new'
  get 'user/login' => 'users#login'
  post 'users/signup' => 'users#signup'
  post 'users/login' => 'users#login_check'
  post 'user/show' => 'users#show'
  
  get 'user/logout' => 'users#logout'
  
  # Routes for Urls
  resources :urls
  get 'url/long' => 'urls#search_longurl' 
  post 'urls/long' => 'urls#create_shorturl'

  # Routes for urlreport
  get 'urlreport/new' => 'urlreports#new'
  get 'urlreport' => 'urlreports#index' 
  
  #Routed for elastic search
  get 'url/search' =>'search#search'

  #Routes for short domain
  resources :short_domain
  post 'short_domain/create' => 'short_domain#create_short_domain'
  
end

ruby-implementation/app/models/urlreport.rb
class Urlreport < ApplicationRecord
  validates :date, :presence => true, :uniqueness => true
  validates :count, :presence => true
end

ruby-implementation/app/controllers/urlreports_controller.rb
class UrlreportsController < ApplicationController
  def new
    @urlreport = Urlreport.new
  end
=begin
  **Request Type:** GET
  **Route Path:** urlreport
  **Description:** Indexes all the records in the urlreports table and show their field on index.html.erb view page.
=end
  def index
    @urlreport = Urlreport.where(date: params[:urlreport][:date])
    if @urlreport == nil
      @url=Urlreport.new
    else
      render 'index'
    end
  end
end

ruby-implementation/app/views/urlreports/index.html.erb
<style>
  
  h2{
    font-family:Georgia,sans-serif;
    color:midnightblue;
  }
 #display {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  #display td, #display th {
    border: 1px solid #ddd;
    padding: 8px;
  }
  #display tr:nth-child(even){background-color: #f2f2f2;}
  #display tr:hover {background-color: #ddd;}
  #display th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: midnightblue;
    color: white;
  }
  button{
    font-family:Georgia;
    font-size:1.2em;
  }
</style>

<div id="display">
  <h2>DAILY REPORTS</h2>
  <table>
    <tr>
      <th>Date</th>
      <th>Count</th>
    </tr>
   
    <% @urlreport.each do |urlreport| %>
      <tr>
        <td><%= urlreport.date %> &nbsp &nbsp</td>
        <td><%= urlreport.count %></td>
      </tr>
    <% end %>
  </table><br/>
  <button>BACK : <%= link_to 'back', urlreport_new_path  %> </button>
</div>

ruby-implementation/app/views/urlreports/new.html.erb
<div class="section">
  <%= form_for @urlreport , url: urlreport_path , method: :get  do |form| %>
    <p>Start Date: <%= form.date_field :date %> </br></p>
    <p>Find : <%=  form.submit 'Search' %></p><br/>
  <% end %>
  <button><%=link_to 'Back', new_url_path %></button>
</div>